from app.core.services.verification import (
    VERIFY_EXPIRED_CALLBACK_ANSWER,
    VERIFY_SUCCESS_CALLBACK_ANSWER,
    VERIFY_SUCCESS_PRIVATE_MESSAGE,
    VERIFY_WRONG_USER_CALLBACK_ANSWER,
)

__all__ = (
    "VERIFY_EXPIRED_CALLBACK_ANSWER",
    "VERIFY_SUCCESS_CALLBACK_ANSWER",
    "VERIFY_SUCCESS_PRIVATE_MESSAGE",
    "VERIFY_WRONG_USER_CALLBACK_ANSWER",
)
